### ISSUE TITLE
v1 release vs semver tag

### ISSUE THREAD

**Issue by jimmymcpeter** [phrase/setup-cli#31]
```yml
- uses: phrase/setup-cli@v1
```
This downloads the hard coded [v1 release](https://github.com/phrase/setup-cli/releases/tag/v1), which results in the warning `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: phrase/setup-cli@v1.`

It does not act like semantic versioning by downloading the latest `v1.0.2` release.  You might need to delete the `v1` release here and then create a `v1` tag that you maintain each release according to semver.

I think your intent was meant to be similar to how [actions/checkout](https://github.com/actions/checkout/tags) does it where `uses: actions/checkout@v4` downloads `v4.1.1` (current) instead of `v4.0.0`.

My workaround for now is `uses: phrase/setup-cli@v1.0.2` and rely on dependabot for updates.

**Comment by jablan** [comment]
@jimmymcpeter could you pls retry with `@v1`, should be resolved
